#!/bin/sh

# Generating html version of markdown
PHTML=$(pandoc --standalone --toc --toc-depth=4 --metadata pagetitle="Faust Manual" --mathjax src/introduction.md src/quick-start.md src/overview.md src/compiling.md src/syntax.md src/compiler.md src/embedding.md src/osc.md src/http.md src/midi.md src/architectures.md src/mathdoc.md src/acknowledgments.md src/tuto-juce.md src/tuto-new-archs.md)

source ../../../script/buildtuto

echo "$RESULT" > manual.html
