#!/bin/bash

DOMAIN="https://faust.grame.fr"
#DOMAIN="file:///home/romain/reps/faustwebsite/site"

DEPLOY=site

BUILDALL=0
VERBOSE=0
CPLARGE=0

while [ $1 ]
do
	p=$1
  if [ $p = "-a" ]; then
    BUILDALL=1
		CPLARGE=1
  elif [ "$p" = "-v" ]; then
    VERBOSE=1
  elif [ "$p" = "-cpl" ]; then
    CPLARGE=1
  elif [ "$p" = "-d" ]; then
    shift
    if [[ -n "$1" ]]; then
			DOMAIN=$1
    else
      echo "No domain specified after -d"
    fi
	elif [ "$p" = "-t" ]; then
    shift
    if [[ -n "$1" ]]; then
			DEPLOY=$1
    else
      echo "No target path specified after -t"
    fi
  fi
  shift
done

if [ $BUILDALL -eq 1 ]; then
  if [ $VERBOSE -eq 1 ]; then
    echo "Building examples"
  fi
  cd src/doc/examples
  ./build -d "$DOMAIN"
  if [ $VERBOSE -eq 1 ]; then
    echo "Building libraries doc"
  fi  
  cd ../libraries 
  ./build
  if [ $VERBOSE -eq 1 ]; then
    echo "Building Faust manual"
  fi
  cd ../manual
  ./build -d "$DOMAIN"
  if [ $VERBOSE -eq 1 ]; then
    echo "Building tutorials"
  fi
  cd ../tutorials
  ./build -d "$DOMAIN"
  if [ $VERBOSE -eq 1 ]; then
    echo "Building downloads"
  fi
  cd ../../downloads
  ./build -d "$DOMAIN"
  if [ $VERBOSE -eq 1 ]; then
    echo "Building news"
  fi
  cd ../community/news
  ./build -d "$DOMAIN"
  cd ../../..
fi

HEADERINCLUDES=$(cat lib/header-includes.html)
HEADER=$(cat lib/std-header.html | awk -v includes="$HEADERINCLUDES" '{gsub(/<!-- INCLUDES -->/,includes)}1')
NAVIGATION=$(cat lib/navigation.html)
HEADER=$HEADER"<body>"$NAVIGATION
HEADER=$(echo "$HEADER" | awk -v domain="$DOMAIN" '{gsub(/__DOMAIN__/,domain)}1')
FOOTERCONTENT=$(cat lib/footer-content.html | awk -v domain="$DOMAIN" '{gsub(/__DOMAIN__/,domain)}1')
FOOTERINCLUDES=$(cat lib/footer-includes.html)
PAGECLOSING="</body></html>"
FOOTERL=$FOOTERINCLUDES$PAGECLOSING
FOOTERF=$FOOTERCONTENT$FOOTERINCLUDES$PAGECLOSING
MDWPH="<main role=\"main\"><div class=\"container default-container\">"
MDWPF="</div></main>"

if [ $VERBOSE -eq 1 ]; then
  echo "Creating site folder"
fi
if [ $BUILDALL -eq 1 ]; then
  rm -rf $DEPLOY
fi

mkdir -p $DEPLOY

cp -r src/img $DEPLOY
cp -r css $DEPLOY

################################################################################
# MAIN PAGE
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating main page"
fi
echo "$HEADER$(cat src/main.html)$FOOTERF" > $DEPLOY/index.html

################################################################################
# DOC/LEARN
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating doc index page"
fi
mkdir -p $DEPLOY/doc
echo "$HEADER$MDWPH$(pandoc src/doc/doc.md)$MDWPF$FOOTERF" > $DEPLOY/doc/index.html

################################################################################
# MANUAL
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating manual page"
fi
mkdir -p $DEPLOY/doc/manual
if [ $CPLARGE -eq 1 ]; then
	cp -r src/doc/manual/img $DEPLOY/doc/manual/img
	cp -r src/doc/manual/misc $DEPLOY/doc/manual/misc
fi 
echo "$HEADER$(cat src/doc/manual/manual.html)$FOOTERL" > $DEPLOY/doc/manual/index.html

################################################################################
# LIBRARIES DOC
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating libraries doc page"
fi
mkdir -p $DEPLOY/doc/libraries
echo "$HEADER$(cat src/doc/libraries/libraries.html)$FOOTERL" > $DEPLOY/doc/libraries/index.html

################################################################################
# TUTORIALS
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating tutorials page"
fi
mkdir -p $DEPLOY/doc/tutorials
if [ $CPLARGE -eq 1 ]; then
	cp -r src/doc/tutorials/img $DEPLOY/doc/tutorials/img
	cp -r src/doc/tutorials/misc $DEPLOY/doc/tutorials/misc
fi
echo "$HEADER$(cat src/doc/tutorials/tutorials.html)$FOOTERL" > $DEPLOY/doc/tutorials/index.html

################################################################################
# EXAMPLES
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating examples page"
fi
mkdir -p $DEPLOY/doc/examples
if [ $CPLARGE -eq 1 ]; then
	cp -r src/doc/examples/img $DEPLOY/doc/examples/img 
fi
echo "$HEADER$(cat src/doc/examples/examples.html)$FOOTERL" > $DEPLOY/doc/examples/index.html

################################################################################
# DOWNLOADS
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating downloads page"
fi
mkdir -p $DEPLOY/downloads
echo "$HEADER$(cat src/downloads/downloads.html)$FOOTERL" > $DEPLOY/downloads/index.html

################################################################################
# TOOLS
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating tools index page"
fi
mkdir -p $DEPLOY/tools
echo "$HEADER$MDWPH$(pandoc src/tools/tools.md)$MDWPF$FOOTERF" > $DEPLOY/tools/index.html

################################################################################
# EDITOR
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating editor page"
fi
if [ $CPLARGE -eq 1 ]; then
	cp -r src/tools/editor $DEPLOY/tools
	cat src/tools/editor/index.html | awk -v includes="$HEADERINCLUDES" '/<\/head>/{print includes}1' | awk -v nav="$NAVIGATION<main role=\"main\"><div class=\"navzone\"></div><div class=\"container-fluid\"><div class=\"row\">" '/<div class=\"application\">/{print nav}1' | awk '/<script src=\"codemirror\/lib\/codemirror.js\">/{print "</div></main>"}1' | awk '{gsub(/<img src=\"faust-logo.png\" width=58px alt=\"LOGO\">/,"")}1' | awk -v domain="$DOMAIN" '{gsub(/__DOMAIN__/,domain)}1' > $DEPLOY/tools/editor/index.html
fi

################################################################################
# PLAYGROUND
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating playground page"
fi
# TODO: we coul improve the integration of the Faust playground
if [ $CPLARGE -eq 1 ]; then
	cp -r src/tools/playground $DEPLOY/tools
fi

################################################################################
# ONLINE COMPILER
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating online compiler page"
fi
# TODO: we coul improve the integration of the online compiler
if [ $CPLARGE -eq 1 ]; then
	cp -r src/tools/onlinecompiler $DEPLOY/tools
fi

################################################################################
# COMMUNITY
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating community index page"
fi
mkdir -p $DEPLOY/community
echo "$HEADER$MDWPH$(pandoc src/community/community.md)$MDWPF$FOOTERF" > $DEPLOY/community/index.html

################################################################################
# NEWS
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating news page"
fi
mkdir -p $DEPLOY/community/news
cp -r src/community/news/img $DEPLOY/community/news
echo "$HEADER$(cat src/community/news/news.html)$FOOTERL" > $DEPLOY/community/news/index.html

################################################################################
# MAILING-LISTS
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating mailinglists page"
fi
mkdir -p $DEPLOY/community/mailing-lists
echo "$HEADER$MDWPH$(pandoc src/community/mailing-lists/mailing-lists.md)$MDWPF$FOOTERF" > $DEPLOY/community/mailing-lists/index.html

################################################################################
# FAUST CONFERENCE
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating Faust conference page"
fi
mkdir -p $DEPLOY/community/ifc
cp -r src/community/ifc/img $DEPLOY/community/ifc
echo "$HEADER$MDWPH$(pandoc src/community/ifc/ifc.md)$MDWPF$FOOTERF" > $DEPLOY/community/ifc/index.html

################################################################################
# ACADEMIC PUBLICATIONS
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating publications page"
fi
mkdir -p $DEPLOY/community/publications
echo "$HEADER$MDWPH$(pandoc src/community/publications/publications.md)$MDWPF$FOOTERF" > $DEPLOY/community/publications/index.html

################################################################################
# PRESS
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating press page"
fi
mkdir -p $DEPLOY/community/press
echo "$HEADER$MDWPH$(pandoc src/community/press/press.md)$MDWPF$FOOTERF" > $DEPLOY/community/press/index.html

################################################################################
# BUG
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating bug page"
fi
mkdir -p $DEPLOY/community/bug
echo "$HEADER$MDWPH$(pandoc src/community/bug/bug.md)$MDWPF$FOOTERF" > $DEPLOY/community/bug/index.html

################################################################################
# SPONSORS
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating sponsors page"
fi
mkdir -p $DEPLOY/community/sponsors
cp -r src/community/sponsors/img $DEPLOY/community/sponsors
echo "$HEADER$(cat src/community/sponsors/sponsors.html)$FOOTERF" > $DEPLOY/community/sponsors/index.html

################################################################################
# MADE WITH FAUST
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating made with faust page"
fi
mkdir -p $DEPLOY/community/made-with-faust
cp -r src/community/made-with-faust/img $DEPLOY/community/made-with-faust
echo "$HEADER$(cat src/community/made-with-faust/made-with-faust.html)$FOOTERF" > $DEPLOY/community/made-with-faust/index.html

################################################################################
# MI FAUST
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating MI Faust page"
fi
mkdir -p $DEPLOY/community/made-with-faust/mi-faust
cp -r src/community/made-with-faust/mi-faust/img $DEPLOY/community/made-with-faust/mi-faust
cp -r src/community/made-with-faust/mi-faust/code $DEPLOY/community/made-with-faust/mi-faust
echo "$HEADER$MDWPH$(pandoc src/community/made-with-faust/mi-faust/mi-faust.md)$MDWPF$FOOTERF" > $DEPLOY/community/made-with-faust/mi-faust/index.html

################################################################################
# MISC
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating misc page"
fi
mkdir -p $DEPLOY/community/misc
cp -r src/community/misc/img $DEPLOY/community/misc
echo "$HEADER$MDWPH$(pandoc src/community/misc/misc.md)$MDWPF$FOOTERF" > $DEPLOY/community/misc/index.html

################################################################################
# SHOWCASE
################################################################################
if [ $VERBOSE -eq 1 ]; then
  echo "Generating showcase"
fi
mkdir -p $DEPLOY/showcase
cp -r src/showcase/img $DEPLOY/showcase
echo "$HEADER$(cat src/showcase/showcase.html)$FOOTERF" > $DEPLOY/showcase/index.html
