#!/bin/sh

#DOMAIN="https://faust.grame.fr/new"
DOMAIN="file:///home/romain/reps/faustwebsite/site"
#DOMAIN="127.0.0.1:8000"

INCLUDES=$(cat lib/includes.html)
HEADER=$(cat lib/std-header.html | awk -v includes="$INCLUDES" '{gsub(/<!-- INCLUDES -->/,includes)}1')
NAVIGATION=$(cat lib/navigation.html)
HEADER=$HEADER"<body>"$NAVIGATION
HEADER=$(echo "$HEADER" | awk -v domain="$DOMAIN" '{gsub(/__DOMAIN__/,domain)}1')
FOOTERF=$(cat lib/footer-full.html)
FOOTERL=$(cat lib/footer-light.html)
MDWPH="<main role=\"main\"><div class=\"container default-container\">"
MDWPF="</div></main>"

rm -rf site
mkdir site

cp -r src/img site
cp -r css site

echo "$HEADER$(cat src/main.html)$FOOTERF" > site/index.html

mkdir site/doc
echo "$HEADER$MDWPH$(pandoc src/doc/doc.md)$MDWPF$FOOTERF" > site/doc/index.html

mkdir site/doc/libraries
echo "$HEADER$(cat src/doc/libraries/libraries.html)$FOOTERL" > site/doc/libraries/index.html

mkdir site/doc/manual
cp -r src/doc/manual/img site/doc/manual/img
cp -r src/doc/manual/misc site/doc/manual/misc 
echo "$HEADER$(cat src/doc/manual/manual.html)$FOOTERL" > site/doc/manual/index.html

mkdir site/community
mkdir site/community/news
echo "$HEADER$MDWPH$(pandoc src/community/news/news.md)$MDWPF$FOOTERF" > site/community/news/index.html

mkdir site/tools
echo "$HEADER$MDWPH$(pandoc src/tools/tools.md)$MDWPF$FOOTERF" > site/tools/index.html

cp -r src/tools/editor site/tools
cat site/tools/editor/index.html | awk -v includes="$INCLUDES" '/<\/head>/{print includes}1' | awk -v nav="$NAVIGATION<main role=\"main\"><div class=\"container-fluid\"><div class=\"navzone\"></div><div class=\"row\">" '/<div class=\"application\">/{print nav}1' | awk '/<script src=\"codemirror\/lib\/codemirror.js\">/{print "</div></main>"}1' | awk -v domain="$DOMAIN" '{gsub(/__DOMAIN__/,domain)}1' > site/tools/editor/index2.html
