#!/bin/sh

MDFILES=$(ls -r src | awk '$0="src/"$0')

# Generating html version of markdown
PHTML=$(pandoc --standalone --toc --toc-depth=1 --metadata pagetitle="News" --mathjax $MDFILES)

source ../../../script/buildtuto

echo "$RESULT" > news.html
