#!/bin/bash

while [ $1 ]
do
	p=$1
  if [ "$p" = "-d" ]; then
    shift
    if [[ -n "$1" ]]; then
			DOMAIN=$1
    else
      echo "No domain specified after -d"
    fi
  fi
  shift
done

MDFILES=$(ls -r src | awk '$0="src/"$0')

CURRENTFOLDER="/community/news/"

# Generating html version of markdown
PHTML=$(pandoc --standalone --toc --toc-depth=1 --metadata pagetitle="News" --mathjax $MDFILES)

source ../../../script/buildtuto

echo "$RESULT" > news.html
