#!/bin/sh

while [ $1 ]
do
	p=$1
  if [ "$p" = "-d" ]; then
    shift
    if [[ -n "$1" ]]; then
			DOMAIN=$1
    else
      echo "No domain specified after -d"
    fi
  fi
  shift
done

# Generating html version of markdown
PHTML=$(pandoc --standalone --toc --toc-depth=4 --metadata pagetitle="Faust Tutorials" --mathjax src/faust-tutorials.md src/tuto-juce.md)

source ../../../script/buildtuto

echo "$RESULT" > tutorials.html
