#!/bin/bash

../../../config

while [ $1 ]
do
	p=$1
  if [ "$p" = "-d" ]; then
    shift
    if [[ -n "$1" ]]; then
			DOMAIN=$1
    else
      echo "No domain specified after -d"
    fi
  fi
  shift
done

FAUSTEXAMPLES="../../../../faust/examples"

rm -rf img
mkdir img
mkdir img/src

rm -rf src/generated
mkdir src/generated

for folder in $(ls "$FAUSTEXAMPLES")
do
  if [ -d "$FAUSTEXAMPLES/$folder" ]
  then
    CURRENTFILE="src/generated/$folder.md"
    FILECONTENT="# $folder"$'\n\n' 
    for exFile in $(ls "$FAUSTEXAMPLES/$folder")
    do
      if [[ $exFile == *".dsp" && $exFile != "multibandFilter.dsp" && $exFile != "guitarix.dsp" && $exFile != "mixer.dsp" ]]
      then 
        FILECONTENT="$FILECONTENT## ${exFile%.dsp}"$'\n\n'
        FILECONTENT="$FILECONTENT<!-- faust-run -->"$'\n```\n'
        FILECONTENT="$FILECONTENT$(cat $FAUSTEXAMPLES/$folder/$exFile)"$'\n```\n'
        FILECONTENT="$FILECONTENT<!-- /faust-run -->"$'\n\n'
      fi
    done
    echo "$FILECONTENT" > "$CURRENTFILE"
    FILESLIST="$FILESLIST $CURRENTFILE"
  fi
done

CURRENTFOLDER="/doc/examples/"

# Generating html version of markdown
PHTML=$(pandoc --standalone --toc --toc-depth=4 --metadata pagetitle="Faust Examples" --mathjax src/faust-examples.md $FILESLIST)

source ../../../script/buildtuto

echo "$RESULT" > examples.html
